const fs = require('fs');
let data = fs.readFileSync('src/data.ts', 'utf8');

data = data.replace(/'footer\.slogan': 'Precision built\. Dependably delivered\.',[\s\S]*?'quote\.sticky': 'Demander un devis',/, `'footer.contact': 'Contact',
    'footer.slogan': 'Precision built. Dependably delivered.',
    'footer.rights': 'All rights reserved.',
    'footer.links': 'Quick Links',
    'footer.connect': 'Connect',
    'whatsapp.chat': 'Chat on WhatsApp',
    'lang.switch': 'Switch to French',
    'quote.sticky': 'Request a Quote',
    'wizard.title': 'Project Request Form',
    'wizard.step1': 'Project Type',
    'wizard.step2': 'Property Details',
    'wizard.step3': 'Scope of Work',
    'wizard.step4': 'Budget & Timeline',
    'wizard.step5': 'Upload Photos / Drawings',
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.projects': 'Portfolio',
    'nav.insights': 'Insights',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.portal': 'Portal',
    'wizard.step6': 'Your Contact Information'
  },
  fr: {
    'home.hero.title': 'Construit avec précision.<br><i class="font-normal text-steel-blue">Livré avec fiabilité.</i>',
    'home.hero.sub': 'Ingénierie, construction, aménagement intérieur et gestion des installations en Afrique de l\\'Ouest.',
    'home.hero.cta1': 'Demander un devis',
    'home.hero.cta2': 'Voir nos projets',
    'home.trust1': '150+ Projets réalisés',
    'home.trust2': 'Commercial et Industriel',
    'home.trust3': '98% de satisfaction client',
    'home.trust4': 'Processus certifiés ISO',
    'home.quick.about': 'À propos',
    'home.quick.aboutp': 'Découvrez notre vision et nos valeurs.',
    'home.quick.read': 'En savoir plus',
    'home.quick.services': 'Nos Services',
    'home.quick.servicesp': 'De l\\'ingénierie à la gestion des installations.',
    'home.quick.explore': 'Explorer',
    'home.quick.projects': 'Portfolio',
    'home.quick.projectsp': 'Voir nos projets réalisés.',
    'home.quick.view': 'Voir',
    'about.title': 'À propos de Glasswater',
    'about.desc': 'Nous sommes une entreprise intégrée de construction, d\\'ingénierie, d\\'aménagement intérieur et de gestion des installations, réalisant des projets commerciaux, industriels, hôteliers, institutionnels et résidentiels en Afrique de l\\'Ouest.',
    'about.values': 'Nos Valeurs',
    'about.vision': 'Notre Vision',
    'about.visiontext': 'Devenir la société de construction, d\\'aménagement et de solutions de bâtiment la plus fiable en Afrique de l\\'Ouest, reconnue pour sa précision, son innovation et sa fiabilité.',
    'services.title': 'Nos Solutions',
    'services.sub': 'Services complets pour tout le cycle de vie du projet',
    'services.eng': 'Ingénierie',
    'services.engp': 'Structure, CVC, et gestion de projet.',
    'services.const': 'Construction',
    'services.constp': 'Nouveaux bâtiments, rénovations et supervision de chantier.',
    'services.fit': 'Aménagement intérieur',
    'services.fitp': 'Bureaux, hôtellerie et intérieurs résidentiels.',
    'services.fin': 'Travaux de finition',
    'services.finp': 'Peinture, revêtements de sol, menuiserie, etc.',
    'services.water': 'Étanchéité et protection',
    'services.waterp': 'Solutions pour toits, sous‑sols et remontées capillaires.',
    'services.pool': 'Ingénierie des piscines',
    'services.poolp': 'Conception, construction, filtration et entretien.',
    'services.fm': 'Gestion des installations',
    'services.fmp': 'Maintenance, gestion d\\'actifs et d\\'énergie.',
    'projects.title': 'Portfolio de Projets',
    'projects.sub': 'Excellence à chaque livraison',
    'insights.title': 'Centre de Connaissances',
    'insights.sub': 'Conseils d\\'experts pour vos projets',
    'faq.title': 'Questions Fréquentes',
    'faq.sub': 'Réponses rapides aux questions courantes',
    'reviews.title': 'Écrire un Avis',
    'reviews.sub': 'Partagez votre expérience avec Glasswater',
    'reviews.submit': 'Envoyer l\\'avis',
    'reviews.latest': 'Derniers avis',
    'contact.title': 'Contactez‑nous',
    'contact.sub': 'Commencez votre projet par une conversation',
    'contact.send': 'Envoyer le message',
    'contact.info': 'Contactez‑nous',
    'contact.infop': 'Nous répondons à toutes les demandes sous 24h.',
    'contact.follow': 'Suivez‑nous',
    'careers.title': 'Carrières',
    'careers.novac': 'Aucun Poste Vacant',
    'careers.novacp': 'Nous n\\'avons actuellement aucun poste ouvert. Veuillez revenir plus tard ou nous vous tiendrons informé des opportunités.',
    'careers.cv': 'Vous pouvez toujours envoyer votre CV à <strong>glasswaterfits@gmail.com</strong> pour une future considération.',
    'portal.title': 'Portail Client',
    'portal.sub': 'Accédez en toute sécurité à vos devis, factures, reçus et documents de projet.',
    'portal.login': 'Connectez‑vous avec votre numéro de référence',
    'portal.enter': 'Entrez la référence unique fournie dans votre e‑mail de bienvenue.',
    'portal.loginbtn': 'Se connecter',
    'portal.demo': '*Ceci est une démo. En production, cela sera connecté à votre stockage sécurisé de documents.',
    'portal.search_another': 'Rechercher un autre code',
    'portal.download_pdf': 'Télécharger le PDF',
    'portal.view_file': 'Voir le fichier joint',
    'portal.print': 'Imprimer',
    'portal.doc_error': 'Aucun document trouvé pour le code de référence',
    'footer.contact': 'Contact',
    'footer.slogan': 'Construit avec précision. Livré avec fiabilité.',
    'footer.rights': 'Tous droits réservés.',
    'footer.links': 'Liens rapides',
    'footer.connect': 'Connectez-vous',
    'whatsapp.chat': 'Discuter sur WhatsApp',
    'lang.switch': 'Passer à l\\'anglais',
    'quote.sticky': 'Demander un devis'`);

fs.writeFileSync('src/data.ts', data);
