const fs = require('fs');
let data = fs.readFileSync('src/data.ts', 'utf8');

const wizardEn = `
    'wizard.type_select': 'Select type...',
    'wizard.new_build': 'New Build',
    'wizard.renovation': 'Renovation',
    'wizard.fit_out': 'Fit-Out',
    'wizard.maintenance': 'Maintenance',
    'wizard.waterproofing': 'Waterproofing',
    'wizard.address': 'Address',
    'wizard.scope_desc': 'Describe your needs...',
    'wizard.electrical': 'Electrical',
    'wizard.plumbing': 'Plumbing',
    'wizard.carpentry': 'Carpentry',
    'wizard.painting': 'Painting',
    'wizard.budget_select': 'Select budget range...',
    'wizard.under_10k': 'Under GHS 10,000',
    'wizard.budget_1': 'GHS 10,000 – 50,000',
    'wizard.budget_2': 'GHS 50,000 – 100,000',
    'wizard.budget_3': 'GHS 100,000 – 500,000',
    'wizard.over_500k': 'Over GHS 500,000',
    'wizard.urgency_select': 'Urgency...',
    'wizard.immediate': 'Immediate (within 1 week)',
    'wizard.soon': 'Soon (1-4 weeks)',
    'wizard.planned': 'Planned (1-3 months)',
    'wizard.max_files': 'Max 5 files (images, PDFs, DWG)',
    'wizard.email': 'Email',
    'wizard.phone': 'Phone',
    'wizard.whatsapp': 'WhatsApp',
    'wizard.fullname': 'Full Name',
    'wizard.next': 'Next',
    'wizard.prev': 'Back',
    'wizard.submit': 'Submit',
    'wizard.submit_success': 'Thank you! We will review your project and get back to you within 24 hours.',`;

const wizardFr = `
    'wizard.type_select': 'Sélectionner le type...',
    'wizard.new_build': 'Nouvelle construction',
    'wizard.renovation': 'Rénovation',
    'wizard.fit_out': 'Aménagement intérieur',
    'wizard.maintenance': 'Maintenance',
    'wizard.waterproofing': 'Étanchéité',
    'wizard.address': 'Adresse',
    'wizard.scope_desc': 'Décrivez vos besoins...',
    'wizard.electrical': 'Électricité',
    'wizard.plumbing': 'Plomberie',
    'wizard.carpentry': 'Menuiserie',
    'wizard.painting': 'Peinture',
    'wizard.budget_select': 'Sélectionner le budget...',
    'wizard.under_10k': 'Moins de 10 000 GHS',
    'wizard.budget_1': '10 000 GHS – 50 000 GHS',
    'wizard.budget_2': '50 000 GHS – 100 000 GHS',
    'wizard.budget_3': '100 000 GHS – 500 000 GHS',
    'wizard.over_500k': 'Plus de 500 000 GHS',
    'wizard.urgency_select': 'Urgence...',
    'wizard.immediate': 'Immédiat (sous 1 semaine)',
    'wizard.soon': 'Bientôt (1-4 semaines)',
    'wizard.planned': 'Prévu (1-3 mois)',
    'wizard.max_files': 'Max 5 fichiers (images, PDF, DWG)',
    'wizard.email': 'E-mail',
    'wizard.phone': 'Téléphone',
    'wizard.whatsapp': 'WhatsApp',
    'wizard.fullname': 'Nom complet',
    'wizard.next': 'Suivant',
    'wizard.prev': 'Retour',
    'wizard.submit': 'Envoyer',
    'wizard.submit_success': 'Merci ! Nous examinerons votre projet et vous répondrons sous 24 heures.',`;

data = data.replace(/'wizard\.step1': 'Project Type',/, wizardEn + `\n    'wizard.step1': 'Project Type',`);
data = data.replace(/'wizard\.step1': 'Type de projet',/, wizardFr + `\n    'wizard.step1': 'Type de projet',`);

fs.writeFileSync('src/data.ts', data);
