const fs = require('fs');

let data = `
import { Page } from './context/NavigationContext';

export const translations: Record<string, Record<string, string>> = {
  en: {
    'home.hero.title': 'Precision built.<br><i class="font-normal text-steel-blue">Dependably delivered.</i>',
    'home.hero.sub': 'West Africa\\'s integrated engineering, construction, interior fit‑out and facilities management company.',
    'home.hero.cta1': 'Request Quote',
    'home.hero.cta2': 'View Our Work',
    'home.trust1': '150+ Projects Delivered',
    'home.trust2': 'Commercial & Industrial',
    'home.trust3': '98% Client Satisfaction',
    'home.trust4': 'ISO Certified Processes',
    'home.quick.about': 'About Us',
    'home.quick.aboutp': 'Discover our vision and core values.',
    'home.quick.read': 'Read More',
    'home.quick.services': 'Our Services',
    'home.quick.servicesp': 'From structural engineering to facilities management.',
    'home.quick.explore': 'Explore',
    'home.quick.projects': 'Project Portfolio',
    'home.quick.projectsp': 'View our track record of successful deliveries.',
    'home.quick.view': 'View Portfolio',
    'about.title': 'About Glasswater',
    'about.desc': 'We are an integrated construction, engineering, interior fit‑out and facilities management company delivering commercial, industrial, hospitality, institutional and residential projects across West Africa.',
    'about.values': 'Our Core Values',
    'about.vision': 'Our Vision',
    'about.visiontext': 'To become West Africa\\'s most trusted fit‑out, engineering and building solutions company known for precision, innovation and dependable project delivery.',
    'services.title': 'Our Solutions',
    'services.sub': 'Comprehensive services across the project lifecycle',
    'services.eng': 'Engineering Services',
    'services.engp': 'Structural, MEP, and project management.',
    'services.const': 'Construction Services',
    'services.constp': 'New builds, renovations, and site management.',
    'services.fit': 'Interior Fit‑Out',
    'services.fitp': 'Office, hospitality, and residential interiors.',
    'services.fin': 'Finishing Works',
    'services.finp': 'Painting, flooring, carpentry, and more.',
    'services.water': 'Waterproofing & Protection',
    'services.waterp': 'Roof, basement, and damp‑proofing solutions.',
    'services.pool': 'Swimming Pool Engineering',
    'services.poolp': 'Design, build, filtration, and maintenance.',
    'services.fm': 'Facilities Management',
    'services.fmp': 'Maintenance, asset, and energy management.',
    'projects.title': 'Project Portfolio',
    'projects.sub': 'Excellence in every delivery',
    'insights.title': 'Knowledge Centre',
    'insights.sub': 'Expert insights for your projects',
    'faq.title': 'Frequently Asked Questions',
    'faq.sub': 'Quick answers to common questions',
    'reviews.title': 'Write Your Review',
    'reviews.sub': 'Share your experience with Glasswater',
    'reviews.submit': 'Submit Review',
    'reviews.latest': 'Latest Reviews',
    'contact.title': 'Contact Us',
    'contact.sub': 'Start your project with a conversation',
    'contact.send': 'Send Message',
    'contact.info': 'Get in touch',
    'contact.infop': 'We respond to all enquiries within 24 hours.',
    'contact.follow': 'Follow Us',
    'careers.title': 'Careers',
    'careers.novac': 'No Open Vacancies',
    'careers.novacp': 'We currently do not have any open positions. Please check back later or we will update you when opportunities arise.',
    'careers.cv': 'You can still send your CV to <strong>glasswaterfits@gmail.com</strong> for future consideration.',
    'portal.title': 'Client Portal',
    'portal.sub': 'Securely access your estimates, invoices, receipts, and project documents.',
    'portal.login': 'Login with your reference number',
    'portal.enter': 'Enter the unique reference provided in your welcome email.',
    'portal.loginbtn': 'Login',
    'portal.demo': '*This is a demo. In production, this will connect to your secure document storage.',
    'portal.try_code': 'Try code:',
    'portal.doc_error_verify': 'Please verify your code and try again.',
    'portal.pdf_error': 'Failed to generate PDF. You can also use the Print button.',
    'portal.doc_access': 'Client Document Access',
    'portal.doc_ref': 'Document Ref:',
    'portal.doc_date': 'Generated Date:',
    'portal.client_name': 'Client Name',
    'portal.contact_phone': 'Contact Phone',
    'portal.email_address': 'Email Address',
    'portal.statement': 'Statement of Accounts',
    'portal.no_items': 'No itemized breakdown is recorded. Please see the attached PDF copy or contact our accounts office.',
    'portal.item_desc': 'Item Description',
    'portal.qty': 'Qty',
    'portal.unit_price': 'Unit Price',
    'portal.line_total': 'Line Total',
    'portal.discount': 'Discount',
    'portal.total_amount': 'Total Amount:',
    'portal.payment_info': 'Payment Information',
    'portal.terms': 'Terms & Important Instructions',
    'portal.thank_you': 'Thank you for choosing Glasswater. We appreciate your valued business.',
    'portal.questions': 'Have questions about this Statement?',
    'portal.get_in_touch': 'Get in touch directly with our support team to verify estimate details or approve work.',
    'portal.email_office': 'Email Office',
    'portal.search_another': 'Search Another Code',
    'portal.download_pdf': 'Download PDF',
    'portal.view_file': 'View Attached File',
    'portal.print': 'Print',
    'portal.doc_error': 'No document found for Reference Code',
    'portal.issued_by': 'Issued By',
    'portal.client_info': 'Client Information',
    'portal.date_issued': 'Date Issued',
    'portal.due_date': 'Due Date',
    'portal.system_status': 'System Status',
    'portal.subject_matter': 'Subject Matter / Scope of Works',
    'portal.statement_accounts': 'Statement of Accounts',
    'portal.item_description': 'Item Description',
    'portal.tax': 'Tax / VAT',
    'portal.grand_total': 'Grand Total',
    'footer.contact': 'Contact',
    'footer.slogan': 'Precision built. Dependably delivered.',
    'footer.rights': 'All rights reserved.',
    'footer.links': 'Quick Links',
    'footer.connect': 'Connect',
    'whatsapp.chat': 'Chat on WhatsApp',
    'lang.switch': 'Switch to French',
    'quote.sticky': 'Request a Quote',
    'wizard.title': 'Project Request Form',
    'wizard.step1': 'Project Type',
    'wizard.step2': 'Property Details',
    'wizard.step3': 'Scope of Work',
    'wizard.step4': 'Budget & Timeline',
    'wizard.step5': 'Upload Photos / Drawings',
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.projects': 'Portfolio',
    'nav.insights': 'Insights',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    'nav.portal': 'Portal',
    'wizard.step6': 'Your Contact Information'
  },
  fr: {
    'home.hero.title': 'Construit avec précision.<br><i class="font-normal text-steel-blue">Livré avec fiabilité.</i>',
    'home.hero.sub': 'Ingénierie, construction, aménagement intérieur et gestion des installations en Afrique de l\\'Ouest.',
    'home.hero.cta1': 'Demander un devis',
    'home.hero.cta2': 'Voir nos projets',
    'home.trust1': '150+ Projets réalisés',
    'home.trust2': 'Commercial et Industriel',
    'home.trust3': '98% de satisfaction client',
    'home.trust4': 'Processus certifiés ISO',
    'home.quick.about': 'À propos',
    'home.quick.aboutp': 'Découvrez notre vision et nos valeurs.',
    'home.quick.read': 'En savoir plus',
    'home.quick.services': 'Nos Services',
    'home.quick.servicesp': 'De l\\'ingénierie à la gestion des installations.',
    'home.quick.explore': 'Explorer',
    'home.quick.projects': 'Portfolio',
    'home.quick.projectsp': 'Voir nos projets réalisés.',
    'home.quick.view': 'Voir',
    'about.title': 'À propos de Glasswater',
    'about.desc': 'Nous sommes une entreprise intégrée de construction, d\\'ingénierie, d\\'aménagement intérieur et de gestion des installations, réalisant des projets commerciaux, industriels, hôteliers, institutionnels et résidentiels en Afrique de l\\'Ouest.',
    'about.values': 'Nos Valeurs',
    'about.vision': 'Notre Vision',
    'about.visiontext': 'Devenir la société de construction, d\\'aménagement et de solutions de bâtiment la plus fiable en Afrique de l\\'Ouest, reconnue pour sa précision, son innovation et sa fiabilité.',
    'services.title': 'Nos Solutions',
    'services.sub': 'Services complets pour tout le cycle de vie du projet',
    'services.eng': 'Ingénierie',
    'services.engp': 'Structure, CVC, et gestion de projet.',
    'services.const': 'Construction',
    'services.constp': 'Nouveaux bâtiments, rénovations et supervision de chantier.',
    'services.fit': 'Aménagement intérieur',
    'services.fitp': 'Bureaux, hôtellerie et intérieurs résidentiels.',
    'services.fin': 'Travaux de finition',
    'services.finp': 'Peinture, revêtements de sol, menuiserie, etc.',
    'services.water': 'Étanchéité et protection',
    'services.waterp': 'Solutions pour toits, sous‑sols et remontées capillaires.',
    'services.pool': 'Ingénierie des piscines',
    'services.poolp': 'Conception, construction, filtration et entretien.',
    'services.fm': 'Gestion des installations',
    'services.fmp': 'Maintenance, gestion d\\'actifs et d\\'énergie.',
    'projects.title': 'Portfolio de Projets',
    'projects.sub': 'Excellence à chaque livraison',
    'insights.title': 'Centre de Connaissances',
    'insights.sub': 'Conseils d\\'experts pour vos projets',
    'faq.title': 'Questions Fréquentes',
    'faq.sub': 'Réponses rapides aux questions courantes',
    'reviews.title': 'Écrire un Avis',
    'reviews.sub': 'Partagez votre expérience avec Glasswater',
    'reviews.submit': 'Envoyer l\\'avis',
    'reviews.latest': 'Derniers avis',
    'contact.title': 'Contactez‑nous',
    'contact.sub': 'Commencez votre projet par une conversation',
    'contact.send': 'Envoyer le message',
    'contact.info': 'Contactez‑nous',
    'contact.infop': 'Nous répondons à toutes les demandes sous 24h.',
    'contact.follow': 'Suivez‑nous',
    'careers.title': 'Carrières',
    'careers.novac': 'Aucun Poste Vacant',
    'careers.novacp': 'Nous n\\'avons actuellement aucun poste ouvert. Veuillez revenir plus tard ou nous vous tiendrons informé des opportunités.',
    'careers.cv': 'Vous pouvez toujours envoyer votre CV à <strong>glasswaterfits@gmail.com</strong> pour une future considération.',
    'portal.title': 'Portail Client',
    'portal.sub': 'Accédez en toute sécurité à vos devis, factures, reçus et documents de projet.',
    'portal.login': 'Connectez‑vous avec votre numéro de référence',
    'portal.enter': 'Entrez la référence unique fournie dans votre e‑mail de bienvenue.',
    'portal.loginbtn': 'Se connecter',
    'portal.demo': '*Ceci est une démo. En production, cela sera connecté à votre stockage sécurisé de documents.',
    'portal.try_code': 'Essayer le code:',
    'portal.doc_error_verify': 'Veuillez vérifier votre code et réessayer.',
    'portal.pdf_error': 'Échec de la génération du PDF. Vous pouvez également utiliser le bouton Imprimer.',
    'portal.doc_access': 'Accès au document client',
    'portal.doc_ref': 'Réf. du document :',
    'portal.doc_date': 'Date de génération :',
    'portal.client_name': 'Nom du client',
    'portal.contact_phone': 'Téléphone',
    'portal.email_address': 'Adresse e-mail',
    'portal.statement': 'Relevé de compte',
    'portal.no_items': 'Aucune ventilation détaillée n\\'est enregistrée. Veuillez consulter la copie PDF jointe ou contacter notre service comptable.',
    'portal.item_desc': 'Description de l\\'article',
    'portal.qty': 'Qté',
    'portal.unit_price': 'Prix unitaire',
    'portal.line_total': 'Total partiel',
    'portal.discount': 'Remise',
    'portal.total_amount': 'Montant total :',
    'portal.payment_info': 'Informations de paiement',
    'portal.terms': 'Conditions et instructions importantes',
    'portal.thank_you': 'Merci d\\'avoir choisi Glasswater. Nous apprécions votre fidélité.',
    'portal.questions': 'Avez-vous des questions concernant ce relevé ?',
    'portal.get_in_touch': 'Contactez directement notre équipe d\\'assistance pour vérifier les détails de l\\'estimation ou approuver les travaux.',
    'portal.email_office': 'Envoyer un e-mail au bureau',
    'portal.search_another': 'Rechercher un autre code',
    'portal.download_pdf': 'Télécharger le PDF',
    'portal.view_file': 'Voir le fichier joint',
    'portal.print': 'Imprimer',
    'portal.doc_error': 'Aucun document trouvé pour le code de référence',
    'portal.issued_by': 'Émis par',
    'portal.client_info': 'Informations du client',
    'portal.date_issued': 'Date d\\'émission',
    'portal.due_date': 'Date d\\'échéance',
    'portal.system_status': 'Statut du système',
    'portal.subject_matter': 'Sujet / Étendue des travaux',
    'portal.statement_accounts': 'Relevé de compte',
    'portal.item_description': 'Description de l\\'article',
    'portal.tax': 'Taxes / TVA',
    'portal.grand_total': 'Total général',
    'footer.contact': 'Contact',
    'footer.slogan': 'Construit avec précision. Livré avec fiabilité.',
    'footer.rights': 'Tous droits réservés.',
    'footer.links': 'Liens rapides',
    'footer.connect': 'Connectez-vous',
    'whatsapp.chat': 'Discuter sur WhatsApp',
    'lang.switch': 'Passer à l\\'anglais',
    'quote.sticky': 'Demander un devis',
    'wizard.title': 'Formulaire de demande de projet',
    'wizard.step1': 'Type de projet',
    'wizard.step2': 'Détails de la propriété',
    'wizard.step3': 'Portée des travaux',
    'wizard.step4': 'Budget et calendrier',
    'wizard.step5': 'Télécharger des photos / plans',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.projects': 'Portfolio',
    'nav.insights': 'Actualités',
    'nav.reviews': 'Avis',
    'nav.contact': 'Contact',
    'nav.portal': 'Portail',
    'wizard.step6': 'Vos coordonnées'
  }
};

export const defaultReviews = [
  {
    name: 'Kofi Mensah',
    location: 'Airport Residential Area, Accra',
    rating: 5,
    text: 'Glasswater completed the fit‑out for our new corporate office ahead of schedule. The craftsmanship in the glass partitioning and finishing is pristine. Highly recommended!',
    date: 1717843200000
  },
  {
    name: 'Naa Adjeley',
    location: 'East Legon, Accra',
    rating: 5,
    text: 'We had persistent dampness and roof leaks in our warehouse for years. Glasswater applied their multi‑layer liquid waterproofing system, and we have been bone dry ever since.',
    date: 1718016000000
  },
  {
    name: 'Ekow Benson',
    location: 'Tema Community 6',
    rating: 4,
    text: 'Superb project management and structural engineering. Their pool construction division is also state‑of‑the‑art. Communication was excellent throughout the project.',
    date: 1718275200000
  }
];
`;

fs.writeFileSync('src/data.ts', data);
