const fs = require('fs');
let data = fs.readFileSync('src/pages/PortalPage.tsx', 'utf8');

data = data.replace(/Statement of Accounts/g, "{t('portal.statement')}");
data = data.replace(/No itemized breakdown is recorded\. Please see the attached PDF copy or contact our accounts office\./g, "{t('portal.no_items')}");
data = data.replace(/>Item Description</g, ">{t('portal.item_desc')}<");
data = data.replace(/>Qty</g, ">{t('portal.qty')}<");
data = data.replace(/>Unit Price</g, ">{t('portal.unit_price')}<");
data = data.replace(/>Line Total</g, ">{t('portal.line_total')}<");
data = data.replace(/Discount \(/g, "{t('portal.discount')} (");
data = data.replace(/>Total Amount:</g, ">{t('portal.total_amount')}<");
data = data.replace(/Payment Information/g, "{t('portal.payment_info')}");
data = data.replace(/Terms \&amp; Important Instructions/g, "{t('portal.terms')}");
data = data.replace(/Thank you for choosing Glasswater\. We appreciate your valued business\./g, "{t('portal.thank_you')}");
data = data.replace(/Have questions about this {t\('portal\.statement'\)}\?/g, "{t('portal.questions')}");
data = data.replace(/Get in touch directly with our support team to verify estimate details or approve work\./g, "{t('portal.get_in_touch')}");
data = data.replace(/>WhatsApp Chat</g, "><MessageCircle size={16} \/> {t('whatsapp.chat')}<");
data = data.replace(/>Email Office</g, "><Mail size={16} \/> {t('portal.email_office')}<");
data = data.replace(/<MessageCircle size=\{16\} \/> <MessageCircle size=\{16\} \/> /g, "<MessageCircle size={16} /> ");
data = data.replace(/<Mail size=\{16\} \/> <Mail size=\{16\} \/> /g, "<Mail size={16} /> ");
fs.writeFileSync('src/pages/PortalPage.tsx', data);
