export const projects = [
  { 
    id: '1',
    title: 'Accra Financial Hub', 
    category: 'Commercial', 
    description: 'Full interior fit‑out and MEP works for a 15‑storey office tower.', 
    image: 'https://lh3.googleusercontent.com/d/17OEVNBh2mvO3MNCzogUGhSgTuTHh2BQk' 
  },
  { 
    id: '2',
    title: 'Labadi Beach Resort', 
    category: 'Hospitality', 
    description: 'Complete renovation and swimming pool engineering.', 
    image: 'https://lh3.googleusercontent.com/d/16rYbGyUo4aXCqVO3fsKTyL4NI7Ww8rnI' 
  },
  { 
    id: '3',
    title: 'Tema Industrial Park', 
    category: 'Industrial', 
    description: 'Construction, waterproofing and finishing for a warehouse complex.', 
    image: 'https://lh3.googleusercontent.com/d/1yybAmLVE2csJ7mUpp1kqgYMA_Jsk4aeZ' 
  }
];

export const posts = [
  {
    slug: 'waterproofing-tips',
    title: 'Temporary Fixes for Leaky Roofs',
    date: '2026-07-09',
    excerpt: 'Quick, safe measures to protect your property until help arrives.',
    category: 'DIY Tips',
    coverImage: 'https://lh3.googleusercontent.com/d/17OEVNBh2mvO3MNCzogUGhSgTuTHh2BQk',
    content: `<p>First, identify the source of the leak. Look for water stains on ceilings or walls.</p>
              <p>Use a waterproof tarp to cover the affected area on the roof. Secure the edges with heavy objects or nails (if safe).</p>
              <p>While DIY fixes buy you time, <strong>Glasswater</strong> provides permanent waterproofing solutions. Contact us for a full assessment.</p>`
  },
  {
    slug: 'maintenance-tips',
    title: 'Preventive Maintenance for Facility Managers',
    date: '2026-07-08',
    excerpt: 'Extend the life of your building systems with our proven checklist.',
    category: 'Maintenance',
    coverImage: 'https://lh3.googleusercontent.com/d/16rYbGyUo4aXCqVO3fsKTyL4NI7Ww8rnI',
    content: `<p>Regular inspections can save up to 30% on repair costs. Schedule quarterly HVAC checks, monthly plumbing inspections, and annual structural reviews.</p>
              <p>Our facilities management team can handle all of this for you. <a href="#contact" data-page="contact">Get in touch</a> to learn more.</p>`
  },
  {
    slug: 'waterproofing-best-practices',
    title: 'Waterproofing Best Practices',
    date: '2026-07-07',
    excerpt: 'Ensure durability in West Africa\'s climate with modern techniques.',
    category: 'Construction',
    coverImage: 'https://lh3.googleusercontent.com/d/1yybAmLVE2csJ7mUpp1kqgYMA_Jsk4aeZ',
    content: `<p>In tropical climates, waterproofing is non‑negotiable. Use liquid‑applied membranes for roofs and crystalline admixtures for concrete foundations.</p>
              <p>Always hire certified professionals – Glasswater\'s team is trained in the latest waterproofing technologies.</p>`
  }
];

export const faqs = [
  { q: 'What areas do you serve?', a: 'We operate across Ghana and West Africa, with a focus on Accra, Kumasi, and Tema.' },
  { q: 'How long does a typical fit‑out take?', a: 'Depending on the scope, most projects range from 4 to 12 weeks.' },
  { q: 'Do you provide warranties?', a: 'Yes, we offer a standard 1‑year warranty on all workmanship and materials.' },
  { q: 'What is your payment structure?', a: 'We typically require a 30% deposit, with progress payments tied to milestones.' },
  { q: 'Can you handle large commercial projects?', a: 'Absolutely. We have extensive experience with office towers, hotels, and industrial complexes.' }
];

export const translations: Record<string, Record<string, string>> = {
  en: {
    'home.hero.title': 'Precision Built.<br><i class="font-normal text-steel-blue">Dependably Delivered.</i>',
    'home.hero.sub': 'Engineering, construction, interior fit‑out and facilities management across West Africa.',
    'home.hero.cta1': 'Request a Consultation',
    'home.hero.cta2': 'View Our Work',
    'home.trust1': '150+ Projects Completed',
    'home.trust2': 'Commercial & Industrial',
    'home.trust3': '98% Client Satisfaction',
    'home.trust4': 'ISO‑Certified Processes',
    'home.quick.about': 'About Us',
    'home.quick.aboutp': 'Learn about our vision and values.',
    'home.quick.read': 'Read more',
    'home.quick.services': 'Our Services',
    'home.quick.servicesp': 'From engineering to facilities management.',
    'home.quick.explore': 'Explore',
    'home.quick.projects': 'Project Portfolio',
    'home.quick.projectsp': 'See our completed projects.',
    'home.quick.view': 'View',
    'about.title': 'About Glasswater',
    'about.desc': 'We are an integrated construction, engineering, interior fit‑out and facilities management company delivering commercial, industrial, hospitality, institutional and residential projects across West Africa.',
    'about.values': 'Our Core Values',
    'about.vision': 'Our Vision',
    'about.visiontext': 'To become West Africa\'s most trusted fit‑out, engineering and building solutions company known for precision, innovation and dependable project delivery.',
    'services.title': 'Our Solutions',
    'services.sub': 'Comprehensive services across the project lifecycle',
    'services.eng': 'Engineering Services',
    'services.engp': 'Structural, MEP, and project management.',
    'services.const': 'Construction Services',
    'services.constp': 'New builds, renovations, and site management.',
    'services.fit': 'Interior Fit‑Out',
    'services.fitp': 'Office, hospitality, and residential interiors.',
    'services.fin': 'Finishing Works',
    'services.finp': 'Painting, flooring, carpentry, and more.',
    'services.water': 'Waterproofing & Protection',
    'services.waterp': 'Roof, basement, and damp‑proofing solutions.',
    'services.pool': 'Swimming Pool Engineering',
    'services.poolp': 'Design, build, filtration, and maintenance.',
    'services.fm': 'Facilities Management',
    'services.fmp': 'Maintenance, asset, and energy management.',
    'projects.title': 'Project Portfolio',
    'projects.sub': 'Excellence in every delivery',
    'insights.title': 'Knowledge Centre',
    'insights.sub': 'Expert insights for your projects',
    'faq.title': 'Frequently Asked Questions',
    'faq.sub': 'Quick answers to common questions',
    'reviews.title': 'Write Your Review',
    'reviews.sub': 'Share your experience with Glasswater',
    'reviews.submit': 'Submit Review',
    'reviews.latest': 'Latest Reviews',
    'contact.title': 'Contact Us',
    'contact.sub': 'Start your project with a conversation',
    'contact.send': 'Send Message',
    'contact.info': 'Get in touch',
    'contact.infop': 'We respond to all enquiries within 24 hours.',
    'contact.follow': 'Follow Us',
    'careers.title': 'Careers',
    'careers.novac': 'No Open Vacancies',
    'careers.novacp': 'We currently do not have any open positions. Please check back later or we will update you when opportunities arise.',
    'careers.cv': 'You can still send your CV to <strong>glasswaterfits@gmail.com</strong> for future consideration.',
    'portal.title': 'Client Portal',
    'portal.sub': 'Securely access your estimates, invoices, receipts, and project documents.',
    'portal.login': 'Login with your reference number',
    'portal.enter': 'Enter the unique reference provided in your welcome email.',
    'portal.loginbtn': 'Login',
    'portal.demo': '*This is a demo. In production, this will connect to your secure document storage.',
    'footer.contact': 'Contact',
    'footer.links': 'Quick Links',
    'footer.connect': 'Connect',
    'quote.sticky': 'Request a Quote',
    'wizard.title': 'Project Request Wizard',
    'wizard.step1': 'Project Type',
    'wizard.step2': 'Property Details',
    'wizard.step3': 'Scope of Work',
    'wizard.step4': 'Budget & Timeline',
    'wizard.step5': 'Upload Photos / Drawings',
    'wizard.step6': 'Your Contact Information'
  },
  fr: {
    'home.hero.title': 'Construit avec précision.<br><i class="font-normal text-steel-blue">Livré avec fiabilité.</i>',
    'home.hero.sub': 'Ingénierie, construction, aménagement intérieur et gestion des installations en Afrique de l\'Ouest.',
    'home.hero.cta1': 'Demander un devis',
    'home.hero.cta2': 'Voir nos projets',
    'home.trust1': '150+ Projets réalisés',
    'home.trust2': 'Commercial et Industriel',
    'home.trust3': '98% de satisfaction client',
    'home.trust4': 'Processus certifiés ISO',
    'home.quick.about': 'À propos',
    'home.quick.aboutp': 'Découvrez notre vision et nos valeurs.',
    'home.quick.read': 'En savoir plus',
    'home.quick.services': 'Nos Services',
    'home.quick.servicesp': 'De l\'ingénierie à la gestion des installations.',
    'home.quick.explore': 'Explorer',
    'home.quick.projects': 'Portfolio',
    'home.quick.projectsp': 'Voir nos projets réalisés.',
    'home.quick.view': 'Voir',
    'about.title': 'À propos de Glasswater',
    'about.desc': 'Nous sommes une entreprise intégrée de construction, d\'ingénierie, d\'aménagement intérieur et de gestion des installations, réalisant des projets commerciaux, industriels, hôteliers, institutionnels et résidentiels en Afrique de l\'Ouest.',
    'about.values': 'Nos Valeurs',
    'about.vision': 'Notre Vision',
    'about.visiontext': 'Devenir la société de construction, d\'aménagement et de solutions de bâtiment la plus fiable en Afrique de l\'Ouest, reconnue pour sa précision, son innovation et sa fiabilité.',
    'services.title': 'Nos Solutions',
    'services.sub': 'Services complets pour tout le cycle de vie du projet',
    'services.eng': 'Ingénierie',
    'services.engp': 'Structure, CVC, et gestion de projet.',
    'services.const': 'Construction',
    'services.constp': 'Nouveaux bâtiments, rénovations et supervision de chantier.',
    'services.fit': 'Aménagement intérieur',
    'services.fitp': 'Bureaux, hôtellerie et intérieurs résidentiels.',
    'services.fin': 'Travaux de finition',
    'services.finp': 'Peinture, revêtements de sol, menuiserie, etc.',
    'services.water': 'Étanchéité et protection',
    'services.waterp': 'Solutions pour toits, sous‑sols et remontées capillaires.',
    'services.pool': 'Ingénierie des piscines',
    'services.poolp': 'Conception, construction, filtration et entretien.',
    'services.fm': 'Gestion des installations',
    'services.fmp': 'Maintenance, gestion d\'actifs et d\'énergie.',
    'projects.title': 'Portfolio de Projets',
    'projects.sub': 'Excellence à chaque livraison',
    'insights.title': 'Centre de Connaissances',
    'insights.sub': 'Conseils d\'experts pour vos projets',
    'faq.title': 'Questions Fréquentes',
    'faq.sub': 'Réponses rapides aux questions courantes',
    'reviews.title': 'Écrire un Avis',
    'reviews.sub': 'Partagez votre expérience avec Glasswater',
    'reviews.submit': 'Envoyer l\'avis',
    'reviews.latest': 'Derniers avis',
    'contact.title': 'Contactez‑nous',
    'contact.sub': 'Commencez votre projet par une conversation',
    'contact.send': 'Envoyer le message',
    'contact.info': 'Contactez‑nous',
    'contact.infop': 'Nous répondons à toutes les demandes sous 24h.',
    'contact.follow': 'Suivez‑nous',
    'careers.title': 'Carrières',
    'careers.novac': 'Aucun Poste Vacant',
    'careers.novacp': 'Nous n\'avons actuellement aucun poste ouvert. Veuillez revenir plus tard ou nous vous tiendrons informé des opportunités.',
    'careers.cv': 'Vous pouvez toujours envoyer votre CV à <strong>glasswaterfits@gmail.com</strong> pour une future considération.',
    'portal.title': 'Portail Client',
    'portal.sub': 'Accédez en toute sécurité à vos devis, factures, reçus et documents de projet.',
    'portal.login': 'Connectez‑vous avec votre numéro de référence',
    'portal.enter': 'Entrez la référence unique fournie dans votre e‑mail de bienvenue.',
    'portal.loginbtn': 'Se connecter',
    'portal.demo': '*Ceci est une démo. En production, cela sera connecté à votre stockage sécurisé de documents.',
    'footer.contact': 'Contact',
    'footer.links': 'Liens rapides',
    'footer.connect': 'Connectez‑vous',
    'quote.sticky': 'Demander un devis',
    'wizard.title': 'Assistant de demande de projet',
    'wizard.step1': 'Type de projet',
    'wizard.step2': 'Détails de la propriété',
    'wizard.step3': 'Portée des travaux',
    'wizard.step4': 'Budget et calendrier',
    'wizard.step5': 'Télécharger des photos / plans',
    'wizard.step6': 'Vos coordonnées'
  }
};

export const defaultReviews = [
  {
    name: 'Kofi Mensah',
    location: 'Airport Residential Area, Accra',
    rating: 5,
    text: 'Glasswater completed the fit‑out for our new corporate office ahead of schedule. The craftsmanship in the glass partitioning and finishing is pristine. Highly recommended!',
    date: 1717843200000
  },
  {
    name: 'Naa Adjeley',
    location: 'East Legon, Accra',
    rating: 5,
    text: 'We had persistent dampness and roof leaks in our warehouse for years. Glasswater applied their multi‑layer liquid waterproofing system, and we have been bone dry ever since.',
    date: 1718016000000
  },
  {
    name: 'Ekow Benson',
    location: 'Tema Community 6',
    rating: 4,
    text: 'Superb project management and structural engineering. Their pool construction division is also state‑of‑the‑art. Communication was excellent throughout the project.',
    date: 1718275200000
  }
];

