
export const projectsEn = [
  { id: '1', title: 'Accra Financial Hub', category: 'Commercial', description: 'Full interior fit‑out and MEP works for a 15‑storey office tower.', image: 'https://lh3.googleusercontent.com/d/17OEVNBh2mvO3MNCzogUGhSgTuTHh2BQk' },
  { id: '2', title: 'Labadi Beach Resort', category: 'Hospitality', description: 'Complete renovation and swimming pool engineering.', image: 'https://lh3.googleusercontent.com/d/16rYbGyUo4aXCqVO3fsKTyL4NI7Ww8rnI' },
  { id: '3', title: 'Tema Industrial Park', category: 'Industrial', description: 'Construction, waterproofing and finishing for a warehouse complex.', image: 'https://lh3.googleusercontent.com/d/1yybAmLVE2csJ7mUpp1kqgYMA_Jsk4aeZ' }
];
export const projectsFr = [
  { id: '1', title: 'Centre Financier d\'Accra', category: 'Commercial', description: 'Aménagement intérieur complet et travaux MEP pour une tour de bureaux de 15 étages.', image: 'https://lh3.googleusercontent.com/d/17OEVNBh2mvO3MNCzogUGhSgTuTHh2BQk' },
  { id: '2', title: 'Complexe Balnéaire de Labadi', category: 'Hospitalité', description: 'Rénovation complète et ingénierie de piscine.', image: 'https://lh3.googleusercontent.com/d/16rYbGyUo4aXCqVO3fsKTyL4NI7Ww8rnI' },
  { id: '3', title: 'Parc Industriel de Tema', category: 'Industriel', description: 'Construction, imperméabilisation et finition pour un complexe d\'entrepôts.', image: 'https://lh3.googleusercontent.com/d/1yybAmLVE2csJ7mUpp1kqgYMA_Jsk4aeZ' }
];
export const getProjects = (lang: string) => lang === 'fr' ? projectsFr : projectsEn;
export const projects = projectsEn; // fallback for admin



export const postsEn = [
  {
    slug: 'waterproofing-tips',
    title: 'Temporary Fixes for Leaky Roofs',
    date: '2026-07-09',
    excerpt: 'Quick, safe measures to protect your property until help arrives.',
    category: 'DIY Tips',
    coverImage: 'https://lh3.googleusercontent.com/d/17OEVNBh2mvO3MNCzogUGhSgTuTHh2BQk',
    content: `<p>First, identify the source of the leak. Look for water stains on ceilings or walls.</p>
              <p>Use a waterproof tarp to cover the affected area on the roof. Secure the edges with heavy objects or nails (if safe).</p>
              <p>While DIY fixes buy you time, <strong>Glasswater</strong> provides permanent waterproofing solutions. Contact us for a full assessment.</p>`
  },
  {
    slug: 'maintenance-tips',
    title: 'Preventive Maintenance for Facility Managers',
    date: '2026-07-08',
    excerpt: 'Extend the life of your building systems with our proven checklist.',
    category: 'Maintenance',
    coverImage: 'https://lh3.googleusercontent.com/d/16rYbGyUo4aXCqVO3fsKTyL4NI7Ww8rnI',
    content: `<p>Regular inspections can save up to 30% on repair costs. Schedule quarterly HVAC checks, monthly plumbing inspections, and annual structural reviews.</p>
              <p>Our facilities management team can handle all of this for you. <a href="#contact" data-page="contact">Get in touch</a> to learn more.</p>`
  },
  {
    slug: 'waterproofing-best-practices',
    title: 'Waterproofing Best Practices',
    date: '2026-07-07',
    excerpt: 'Ensure durability in West Africa\'s climate with modern techniques.',
    category: 'Construction',
    coverImage: 'https://lh3.googleusercontent.com/d/1yybAmLVE2csJ7mUpp1kqgYMA_Jsk4aeZ',
    content: `<p>In tropical climates, waterproofing is non‑negotiable. Use liquid‑applied membranes for roofs and crystalline admixtures for concrete foundations.</p>
              <p>Always hire certified professionals – Glasswater\'s team is trained in the latest waterproofing technologies.</p>`
  }
];

export const postsFr = [
  {
    slug: 'waterproofing-tips',
    title: 'Solutions temporaires pour les toits qui fuient',
    date: '2026-07-09',
    excerpt: 'Mesures rapides et sûres pour protéger votre propriété en attendant de l\'aide.',
    category: 'Astuces de bricolage',
    coverImage: 'https://lh3.googleusercontent.com/d/17OEVNBh2mvO3MNCzogUGhSgTuTHh2BQk',
    content: `<p>Tout d'abord, identifiez la source de la fuite. Recherchez des taches d'eau sur les plafonds ou les murs.</p>
              <p>Utilisez une bâche imperméable pour couvrir la zone affectée sur le toit. Fixez les bords avec des objets lourds ou des clous (si c'est sûr).</p>
              <p>Bien que les réparations de bricolage vous fassent gagner du temps, <strong>Glasswater</strong> fournit des solutions d'imperméabilisation permanentes. Contactez-nous pour une évaluation complète.</p>`
  },
  {
    slug: 'maintenance-tips',
    title: 'Maintenance préventive pour les gestionnaires d\'installations',
    date: '2026-07-08',
    excerpt: 'Prolongez la durée de vie des systèmes de votre bâtiment avec notre liste de contrôle éprouvée.',
    category: 'Entretien',
    coverImage: 'https://lh3.googleusercontent.com/d/16rYbGyUo4aXCqVO3fsKTyL4NI7Ww8rnI',
    content: `<p>Des inspections régulières peuvent économiser jusqu'à 30 % sur les coûts de réparation. Planifiez des contrôles trimestriels de CVC, des inspections mensuelles de plomberie et des examens structurels annuels.</p>
              <p>Notre équipe de gestion des installations peut s'occuper de tout cela pour vous. <a href="#contact" data-page="contact">Contactez-nous</a> pour en savoir plus.</p>`
  },
  {
    slug: 'waterproofing-best-practices',
    title: 'Meilleures pratiques d\'imperméabilisation',
    date: '2026-07-07',
    excerpt: 'Assurez la durabilité dans le climat de l\'Afrique de l\'Ouest avec des techniques modernes.',
    category: 'Construction',
    coverImage: 'https://lh3.googleusercontent.com/d/1yybAmLVE2csJ7mUpp1kqgYMA_Jsk4aeZ',
    content: `<p>Dans les climats tropicaux, l'imperméabilisation n'est pas négociable. Utilisez des membranes appliquées sous forme liquide pour les toits et des adjuvants cristallins pour les fondations en béton.</p>
              <p>Faites toujours appel à des professionnels certifiés - l'équipe de Glasswater est formée aux dernières technologies d'imperméabilisation.</p>`
  }
];
export const getPosts = (lang: string) => lang === 'fr' ? postsFr : postsEn;
export const posts = postsEn; // fallback for admin



export const faqsEn = [
  { q: 'What areas do you serve?', a: 'We operate across Ghana and West Africa, with a focus on Accra, Kumasi, and Tema.' },
  { q: 'How long does a typical fit‑out take?', a: 'Depending on the scope, most projects range from 4 to 12 weeks.' },
  { q: 'Do you provide warranties?', a: 'Yes, we offer a standard 1‑year warranty on all workmanship and materials.' },
  { q: 'What is your payment structure?', a: 'We typically require a 30% deposit, with progress payments tied to milestones.' },
  { q: 'Can you handle large commercial projects?', a: 'Absolutely. We have extensive experience with office towers, hotels, and industrial complexes.' }
];
export const faqsFr = [
  { q: 'Quelles zones desservez-vous ?', a: 'Nous opérons à travers le Ghana et l\'Afrique de l\'Ouest, avec un accent sur Accra, Kumasi et Tema.' },
  { q: 'Combien de temps dure un aménagement typique ?', a: 'En fonction de la portée, la plupart des projets durent de 4 à 12 semaines.' },
  { q: 'Offrez-vous des garanties ?', a: 'Oui, nous offrons une garantie standard d\'un an sur toute la main-d\'œuvre et les matériaux.' },
  { q: 'Quelle est votre structure de paiement ?', a: 'Nous exigeons généralement un acompte de 30 %, avec des paiements d\'étape liés aux jalons.' },
  { q: 'Pouvez-vous gérer de grands projets commerciaux ?', a: 'Absolument. Nous avons une vaste expérience avec les tours de bureaux, les hôtels et les complexes industriels.' }
];
export const getFaqs = (lang: string) => lang === 'fr' ? faqsFr : faqsEn;
export const faqs = faqsEn;


export const translations: Record<string, Record<string, string>> = {
  en: {

    'hero.title1': 'Precision Built.',
    'hero.title2': 'Dependably Delivered.',
    'hero.desc': 'Engineering, construction, interior fit‑out and facilities management across West Africa.',
    'hero.btn1': 'Request a Consultation',
    'hero.btn2': 'View Our Work',
    'hero.badge': 'Project Showcase',
    
    'comp.careers.title': 'Careers',
    'comp.careers.sub': 'Join our team of precision professionals',
    'comp.industries.title': 'Industries We Serve',
    'comp.industries.sub': 'Tailored solutions for diverse sectors',
    'comp.projects.title': 'Project Portfolio',
    'comp.projects.sub': 'Excellence in every delivery',
    'comp.services.title': 'Our Solutions',
    'comp.services.sub': 'Comprehensive services across the project lifecycle',
    'comp.insights.title': 'Knowledge Centre',
    'comp.insights.sub': 'Expert insights for your projects',
    
    'search.no_results': 'No results found.',
    
    'comp.contact.title': 'Contact Us',
    'comp.contact.sub': 'Start your project with a conversation',
    'comp.contact.success': 'Thank you for your enquiry. Our team will respond within 24 hours.',
    'comp.contact.touch': 'Get in touch',
    'comp.contact.resp': 'We respond to all enquiries within 24 hours.',
    
    'comp.about.title': 'About Glasswater',
    'comp.about.vals1': 'Precision, Integrity, Safety, Innovation',
    'comp.about.vals2': 'Quality, Professionalism, Accountability, Reliability',

    'home.hero.title': 'Precision Built.<br><i class="font-normal text-steel-blue">Dependably Delivered.</i>',
    'home.hero.sub': 'Engineering, construction, interior fit‑out and facilities management across West Africa.',
    'home.hero.cta1': 'Request a Consultation',
    'home.hero.cta2': 'View Our Work',
    'home.trust1': '150+ Projects Completed',
    'home.trust2': 'Commercial & Industrial',
    'home.trust3': '98% Client Satisfaction',
    'home.trust4': 'ISO‑Certified Processes',
    'home.quick.about': 'About Us',
    'home.quick.aboutp': 'Learn about our vision and values.',
    'home.quick.read': 'Read more',
    'home.quick.services': 'Our Services',
    'home.quick.servicesp': 'From engineering to facilities management.',
    'home.quick.explore': 'Explore',
    'home.quick.projects': 'Project Portfolio',
    'home.quick.projectsp': 'See our completed projects.',
    'home.quick.view': 'View',
    'about.title': 'About Glasswater',
    'about.desc': 'We are an integrated construction, engineering, interior fit‑out and facilities management company delivering commercial, industrial, hospitality, institutional and residential projects across West Africa.',
    'about.values': 'Our Core Values',
    'about.vision': 'Our Vision',
    'about.visiontext': 'To become West Africa\'s most trusted fit‑out, engineering and building solutions company known for precision, innovation and dependable project delivery.',
    'services.caps': 'Capabilities',
    'services.title': 'Our Solutions',
    'services.sub': 'Comprehensive services across the project lifecycle',
    'services.eng': 'Engineering Services',
    'services.engp': 'Structural, MEP, and project management.',
    'services.const': 'Construction Services',
    'services.constp': 'New builds, renovations, and site management.',
    'services.fit': 'Interior Fit‑Out',
    'services.fitp': 'Office, hospitality, and residential interiors.',
    'services.fin': 'Finishing Works',
    'services.finp': 'Painting, flooring, carpentry, and more.',
    'services.water': 'Waterproofing & Protection',
    'services.waterp': 'Roof, basement, and damp‑proofing solutions.',
    'services.pool': 'Swimming Pool Engineering',
    'services.poolp': 'Design, build, filtration, and maintenance.',
    'services.fm': 'Facilities Management',
    'services.fmp': 'Maintenance, asset, and energy management.',
    'projects.title': 'Project Portfolio',
    'projects.sub': 'Excellence in every delivery',
    'insights.label': 'Insights & News',
    'insights.title': 'Knowledge Centre',
    'insights.sub': 'Industry trends, company updates, and expert perspectives.',
    'faq.title': 'Frequently Asked Questions',
    'faq.sub': 'Quick answers to common questions',
    'reviews.title': 'Write Your Review',
    'reviews.sub': 'Share your experience with Glasswater',
    'reviews.submit': 'Submit Review',
    'reviews.latest': 'Latest Reviews',
    'contact.title': 'Contact Us',
    'contact.sub': 'Start your project with a conversation',
    'contact.send': 'Send Message',
    
    'contact.service': 'Service Interest',
    'contact.opt_eng': 'Engineering',
    'contact.opt_const': 'Construction',
    'contact.opt_int': 'Interior Fit-Out',
    'contact.opt_fin': 'Finishing Works',
    'contact.opt_water': 'Waterproofing',
    'contact.opt_pool': 'Swimming Pool Engineering',
    'contact.opt_fm': 'Facilities Management',
    'contact.opt_other': 'Other',
    'reviews.feedback': 'Feedback',
    'reviews.rating': 'Rating',
    'reviews.empty': 'No reviews yet. Be the first to share your experience!',
    'post.not_found': 'Article not found.',
    'post.editorial': 'GlassWater Editorial',
    'home.stats.proj': 'Projects',
    'home.stats.comm': 'Commercial',
    'home.stats.sat': 'Satisfaction',
    'home.about_label': 'About Us',
    'home.feat_work': 'Featured Work',
    'home.prem_proj': 'Premium Projects',
    'home.testi': 'Testimonials',
    'home.client_feed': 'Client Feedback',
    'home.know_centre': 'Knowledge Centre',
    'about.label': 'About Us',
    'projects.label': 'Portfolio',
    'projects.value': 'Value',
    'projects.duration': 'Duration',
    'contact.info': 'Get in touch',
    'contact.infop': 'We respond to all enquiries within 24 hours.',
    'contact.follow': 'Follow Us',
    'careers.title': 'Careers',
    'careers.novac': 'No Open Vacancies',
    'careers.novacp': 'We currently do not have any open positions. Please check back later or we will update you when opportunities arise.',
    'careers.cv': 'You can still send your CV to <strong>glasswaterfits@gmail.com</strong> for future consideration.',
    'portal.title': 'View Estimate',
    'portal.sub': 'Securely access your estimates, invoices, receipts, and project documents.',
    'portal.login': 'Login with your reference number',
    'portal.enter': 'Enter the unique reference provided in your welcome email.',
    'portal.loginbtn': 'Login',
    'portal.demo': '*This is a demo. In production, this will connect to your secure document storage.',
    'portal.try_code': 'Try code:',
    'portal.doc_error_verify': 'Please verify your code and try again.',
    'portal.pdf_error': 'Failed to generate PDF. You can also use the Print button.',

    'portal.doc_access': 'Client Document Access',
    'portal.doc_ref': 'Document Ref:',
    'portal.doc_date': 'Generated Date:',
    'portal.client_name': 'Client Name',
    'portal.contact_phone': 'Contact Phone',
    'portal.email_address': 'Email Address',
    'portal.statement': 'Statement of Accounts',
    'portal.no_items': 'No itemized breakdown is recorded. Please see the attached PDF copy or contact our accounts office.',
    'portal.item_desc': 'Item Description',
    'portal.qty': 'Qty',
    'portal.unit_price': 'Unit Price',
    'portal.line_total': 'Line Total',
    'portal.discount': 'Discount',
    'portal.total_amount': 'Total Amount:',
    'portal.payment_info': 'Payment Information',
    'portal.terms': 'Terms & Important Instructions',
    'portal.thank_you': 'Thank you for choosing Glasswater. We appreciate your valued business.',
    'portal.questions': 'Have questions about this Statement?',
    'portal.get_in_touch': 'Get in touch directly with our support team to verify estimate details or approve work.',
    'portal.email_office': 'Email Office',
    'whatsapp.chat': 'Chat on WhatsApp',
    'lang.switch': 'Switch to French',
    'portal.search_another': 'Search Another Code',
    'portal.download_pdf': 'Download PDF',
    'portal.view_file': 'View Attached File',
    'portal.print': 'Print',
    'portal.doc_error': 'No document found for Reference Code',
    'footer.slogan': 'Precision built. Dependably delivered.',
    'footer.rights': 'All rights reserved.',
    'footer.contact': 'Contact',
    'footer.links': 'Quick Links',
    'footer.connect': 'Connect',
    'quote.sticky': 'Request a Quote',
    'wizard.title': 'Project Request Form',
    
    'wizard.type_select': 'Select type...',
    'wizard.new_build': 'New Build',
    'wizard.renovation': 'Renovation',
    'wizard.fit_out': 'Fit-Out',
    'wizard.maintenance': 'Maintenance',
    'wizard.waterproofing': 'Waterproofing',
    
    'wizard.area': 'Floor area (sqm)',
    'wizard.floors': 'Number of floors',
    'wizard.age': 'Property age (years)',
    'wizard.start': 'Desired start date',
    'wizard.address': 'Address',
    'wizard.scope_desc': 'Describe your needs...',
    'wizard.electrical': 'Electrical',
    'wizard.plumbing': 'Plumbing',
    'wizard.carpentry': 'Carpentry',
    'wizard.painting': 'Painting',
    'wizard.budget_select': 'Select budget range...',
    'wizard.under_10k': 'Under GHS 10,000',
    'wizard.budget_1': 'GHS 10,000 – 50,000',
    'wizard.budget_2': 'GHS 50,000 – 100,000',
    'wizard.budget_3': 'GHS 100,000 – 500,000',
    'wizard.over_500k': 'Over GHS 500,000',
    'wizard.urgency_select': 'Urgency...',
    'wizard.immediate': 'Immediate (within 1 week)',
    'wizard.soon': 'Soon (1-4 weeks)',
    'wizard.planned': 'Planned (1-3 months)',
    'wizard.max_files': 'Max 5 files (images, PDFs, DWG)',
    'wizard.email': 'Email',
    'wizard.phone': 'Phone',
    'wizard.whatsapp': 'WhatsApp',
    'wizard.fullname': 'Full Name',
    'wizard.next': 'Next',
    'wizard.prev': 'Back',
    'wizard.submit': 'Submit',
    'wizard.submit_success': 'Thank you! We will review your project and get back to you within 24 hours.',
    'wizard.step1': 'Project Type',
    'wizard.step2': 'Property Details',
    'wizard.step3': 'Scope of Work',
    'wizard.step4': 'Budget & Timeline',
    'wizard.step5': 'Upload Photos / Drawings',
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.projects': 'Portfolio',
    'nav.insights': 'Insights',
    'nav.reviews': 'Reviews',
    'nav.contact': 'Contact',
    
    'nav.quote': 'Quote',
    
    'home.swipe': 'Swipe to explore',
    
    'nav.portal': 'Code',
    'portal.date_issued': 'Date Issued',
    'portal.due_date': 'Due Date',
    'social.facebook': 'Facebook',
    'social.instagram': 'Instagram',
    'social.linkedin': 'LinkedIn',
    'social.whatsapp': 'WhatsApp',
    'social.tiktok': 'TikTok',
    'btn.explore_projects': 'Explore Projects',
    'btn.view_project': 'View Project',
    'btn.all_projects': 'All Projects',

    'wizard.step6': 'Your Contact Information'
  },
  fr: {

    'hero.title1': 'Construit avec précision.',
    'hero.title2': 'Livré avec fiabilité.',
    'hero.desc': 'Ingénierie, construction, aménagement intérieur et gestion des installations à travers l\'Afrique de l\'Ouest.',
    'hero.btn1': 'Demander une consultation',
    'hero.btn2': 'Voir notre travail',
    'hero.badge': 'Vitrine de projets',
    
    'comp.careers.title': 'Carrières',
    'comp.careers.sub': 'Rejoignez notre équipe de professionnels',
    'comp.industries.title': 'Industries desservies',
    'comp.industries.sub': 'Des solutions sur mesure pour divers secteurs',
    'comp.projects.title': 'Portfolio de projets',
    'comp.projects.sub': 'L\'excellence à chaque livraison',
    'comp.services.title': 'Nos Solutions',
    'comp.services.sub': 'Des services complets tout au long du cycle de vie du projet',
    'comp.insights.title': 'Centre de connaissances',
    'comp.insights.sub': 'Conseils d\'experts pour vos projets',
    
    'search.no_results': 'Aucun résultat trouvé.',
    
    'comp.contact.title': 'Contactez-nous',
    'comp.contact.sub': 'Commencez votre projet par une conversation',
    'comp.contact.success': 'Merci pour votre demande. Notre équipe vous répondra sous 24 heures.',
    'comp.contact.touch': 'Contactez-nous',
    'comp.contact.resp': 'Nous répondons à toutes les demandes sous 24 heures.',
    
    'comp.about.title': 'À propos de Glasswater',
    'comp.about.vals1': 'Précision, Intégrité, Sécurité, Innovation',
    'comp.about.vals2': 'Qualité, Professionnalisme, Responsabilité, Fiabilité',

    'home.hero.title': 'Construit avec précision.<br><i class="font-normal text-steel-blue">Livré avec fiabilité.</i>',
    'home.hero.sub': 'Ingénierie, construction, aménagement intérieur et gestion des installations en Afrique de l\'Ouest.',
    'home.hero.cta1': 'Demander un devis',
    'home.hero.cta2': 'Voir nos projets',
    'home.trust1': '150+ Projets réalisés',
    'home.trust2': 'Commercial et Industriel',
    'home.trust3': '98% de satisfaction client',
    'home.trust4': 'Processus certifiés ISO',
    'home.quick.about': 'À propos',
    'home.quick.aboutp': 'Découvrez notre vision et nos valeurs.',
    'home.quick.read': 'En savoir plus',
    'home.quick.services': 'Nos Services',
    'home.quick.servicesp': 'De l\'ingénierie à la gestion des installations.',
    'home.quick.explore': 'Explorer',
    'home.quick.projects': 'Portfolio',
    'home.quick.projectsp': 'Voir nos projets réalisés.',
    'home.quick.view': 'Voir',
    'about.title': 'À propos de Glasswater',
    'about.desc': 'Nous sommes une entreprise intégrée de construction, d\'ingénierie, d\'aménagement intérieur et de gestion des installations, réalisant des projets commerciaux, industriels, hôteliers, institutionnels et résidentiels en Afrique de l\'Ouest.',
    'about.values': 'Nos Valeurs',
    'about.vision': 'Notre Vision',
    'about.visiontext': 'Devenir la société de construction, d\'aménagement et de solutions de bâtiment la plus fiable en Afrique de l\'Ouest, reconnue pour sa précision, son innovation et sa fiabilité.',
    'services.caps': 'Capacités',
    'services.title': 'Nos Solutions',
    'services.sub': 'Services complets pour tout le cycle de vie du projet',
    'services.eng': 'Ingénierie',
    'services.engp': 'Structure, CVC, et gestion de projet.',
    'services.const': 'Construction',
    'services.constp': 'Nouveaux bâtiments, rénovations et supervision de chantier.',
    'services.fit': 'Aménagement intérieur',
    'services.fitp': 'Bureaux, hôtellerie et intérieurs résidentiels.',
    'services.fin': 'Travaux de finition',
    'services.finp': 'Peinture, revêtements de sol, menuiserie, etc.',
    'services.water': 'Étanchéité et protection',
    'services.waterp': 'Solutions pour toits, sous‑sols et remontées capillaires.',
    'services.pool': 'Ingénierie des piscines',
    'services.poolp': 'Conception, construction, filtration et entretien.',
    'services.fm': 'Gestion des installations',
    'services.fmp': 'Maintenance, gestion d\'actifs et d\'énergie.',
    'projects.title': 'Portfolio de Projets',
    'projects.sub': 'Excellence à chaque livraison',
    'insights.label': 'Actualités & Idées',
    'insights.title': 'Centre de Connaissances',
    'insights.sub': 'Tendances de l\'industrie, mises à jour de l\'entreprise et perspectives d\'experts.',
    'faq.title': 'Questions Fréquentes',
    'faq.sub': 'Réponses rapides aux questions courantes',
    'reviews.title': 'Écrire un Avis',
    'reviews.sub': 'Partagez votre expérience avec Glasswater',
    'reviews.submit': 'Envoyer l\'avis',
    'reviews.latest': 'Derniers avis',
    'contact.title': 'Contactez‑nous',
    'contact.sub': 'Commencez votre projet par une conversation',
    'contact.send': 'Envoyer le message',
    
    'contact.service': 'Service d\'intérêt',
    'contact.opt_eng': 'Ingénierie',
    'contact.opt_const': 'Construction',
    'contact.opt_int': 'Aménagement intérieur',
    'contact.opt_fin': 'Travaux de finition',
    'contact.opt_water': 'Étanchéité',
    'contact.opt_pool': 'Ingénierie des piscines',
    'contact.opt_fm': 'Gestion des installations',
    'contact.opt_other': 'Autre',
    'reviews.feedback': 'Retours',
    'reviews.rating': 'Note',
    'reviews.empty': 'Aucun avis pour le moment. Soyez le premier à partager votre expérience !',
    'post.not_found': 'Article non trouvé.',
    'post.editorial': 'Rédaction GlassWater',
    'home.stats.proj': 'Projets',
    'home.stats.comm': 'Commercial',
    'home.stats.sat': 'Satisfaction',
    'home.about_label': 'À propos',
    'home.feat_work': 'Projets en vedette',
    'home.prem_proj': 'Projets Premium',
    'home.testi': 'Témoignages',
    'home.client_feed': 'Retours clients',
    'home.know_centre': 'Centre de connaissances',
    'about.label': 'À propos de nous',
    'projects.label': 'Portfolio',
    'projects.value': 'Valeur',
    'projects.duration': 'Durée',
    'contact.info': 'Contactez‑nous',
    'contact.infop': 'Nous répondons à toutes les demandes sous 24h.',
    'contact.follow': 'Suivez‑nous',
    'careers.title': 'Carrières',
    'careers.novac': 'Aucun Poste Vacant',
    'careers.novacp': 'Nous n\'avons actuellement aucun poste ouvert. Veuillez revenir plus tard ou nous vous tiendrons informé des opportunités.',
    'careers.cv': 'Vous pouvez toujours envoyer votre CV à <strong>glasswaterfits@gmail.com</strong> pour une future considération.',
    'portal.title': 'Voir le devis',
    'portal.sub': 'Accédez en toute sécurité à vos devis, factures, reçus et documents de projet.',
    'portal.login': 'Connectez‑vous avec votre numéro de référence',
    'portal.enter': 'Entrez la référence unique fournie dans votre e‑mail de bienvenue.',
    'portal.loginbtn': 'Se connecter',
    'portal.demo': '*Ceci est une démo. En production, cela sera connecté à votre stockage sécurisé de documents.',
    'portal.try_code': 'Essayer le code:',
    'portal.doc_error_verify': 'Veuillez vérifier votre code et réessayer.',
    'portal.pdf_error': 'Échec de la génération du PDF. Vous pouvez également utiliser le bouton Imprimer.',

    'portal.doc_access': 'Accès au document client',
    'portal.doc_ref': 'Réf. du document :',
    'portal.doc_date': 'Date de génération :',
    'portal.client_name': 'Nom du client',
    'portal.contact_phone': 'Téléphone',
    'portal.email_address': 'Adresse e-mail',
    'portal.statement': 'Relevé de compte',
    'portal.no_items': 'Aucune ventilation détaillée n\'est enregistrée. Veuillez consulter la copie PDF jointe ou contacter notre service comptable.',
    'portal.item_desc': 'Description de l\'article',
    'portal.qty': 'Qté',
    'portal.unit_price': 'Prix unitaire',
    'portal.line_total': 'Total partiel',
    'portal.discount': 'Remise',
    'portal.total_amount': 'Montant total :',
    'portal.payment_info': 'Informations de paiement',
    'portal.terms': 'Conditions et instructions importantes',
    'portal.thank_you': 'Merci d\'avoir choisi Glasswater. Nous apprécions votre fidélité.',
    'portal.questions': 'Avez-vous des questions concernant ce relevé ?',
    'portal.get_in_touch': 'Contactez directement notre équipe d\'assistance pour vérifier les détails de l\'estimation ou approuver les travaux.',
    'portal.email_office': 'Envoyer un e-mail au bureau',
    'whatsapp.chat': 'Discuter sur WhatsApp',
    'lang.switch': 'Passer à l\'anglais',
    'portal.search_another': 'Rechercher un autre code',
    'portal.download_pdf': 'Télécharger le PDF',
    'portal.view_file': 'Voir le fichier joint',
    'portal.print': 'Imprimer',
    'portal.doc_error': 'Aucun document trouvé pour le code de référence',
    'footer.slogan': 'Construit avec précision. Livré avec fiabilité.',
    'footer.rights': 'Tous droits réservés.',
    'footer.contact': 'Contact',
    'footer.links': 'Liens rapides',
    'footer.connect': 'Connectez‑vous',
    'quote.sticky': 'Demander un devis',
    'wizard.title': 'Formulaire de demande de projet',
    
    'wizard.type_select': 'Sélectionner le type...',
    'wizard.new_build': 'Nouvelle construction',
    'wizard.renovation': 'Rénovation',
    'wizard.fit_out': 'Aménagement intérieur',
    'wizard.maintenance': 'Maintenance',
    'wizard.waterproofing': 'Étanchéité',
    
    'wizard.area': 'Superficie (m²)',
    'wizard.floors': 'Nombre d\'étages',
    'wizard.age': 'Âge de la propriété (années)',
    'wizard.start': 'Date de début souhaitée',
    'wizard.address': 'Adresse',
    'wizard.scope_desc': 'Décrivez vos besoins...',
    'wizard.electrical': 'Électricité',
    'wizard.plumbing': 'Plomberie',
    'wizard.carpentry': 'Menuiserie',
    'wizard.painting': 'Peinture',
    'wizard.budget_select': 'Sélectionner le budget...',
    'wizard.under_10k': 'Moins de 10 000 GHS',
    'wizard.budget_1': '10 000 GHS – 50 000 GHS',
    'wizard.budget_2': '50 000 GHS – 100 000 GHS',
    'wizard.budget_3': '100 000 GHS – 500 000 GHS',
    'wizard.over_500k': 'Plus de 500 000 GHS',
    'wizard.urgency_select': 'Urgence...',
    'wizard.immediate': 'Immédiat (sous 1 semaine)',
    'wizard.soon': 'Bientôt (1-4 semaines)',
    'wizard.planned': 'Prévu (1-3 mois)',
    'wizard.max_files': 'Max 5 fichiers (images, PDF, DWG)',
    'wizard.email': 'E-mail',
    'wizard.phone': 'Téléphone',
    'wizard.whatsapp': 'WhatsApp',
    'wizard.fullname': 'Nom complet',
    'wizard.next': 'Suivant',
    'wizard.prev': 'Retour',
    'wizard.submit': 'Envoyer',
    'wizard.submit_success': 'Merci ! Nous examinerons votre projet et vous répondrons sous 24 heures.',
    'wizard.step1': 'Type de projet',
    'wizard.step2': 'Détails de la propriété',
    'wizard.step3': 'Portée des travaux',
    'wizard.step4': 'Budget et calendrier',
    'wizard.step5': 'Télécharger des photos / plans',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.projects': 'Portfolio',
    'nav.insights': 'Actualités',
    'nav.reviews': 'Avis',
    'nav.contact': 'Contact',
    
    'nav.quote': 'Devis',
    'nav.portal': 'Code',
    'portal.date_issued': 'Date d\'émission',
    'portal.due_date': 'Date d\'échéance',
    'social.facebook': 'Facebook',
    'social.instagram': 'Instagram',
    'social.linkedin': 'LinkedIn',
    'social.whatsapp': 'WhatsApp',
    'social.tiktok': 'TikTok',
    'btn.explore_projects': 'Explorer Projets',
    'btn.view_project': 'Voir Projet',
    'btn.all_projects': 'Tous Projets',

    'wizard.step6': 'Vos coordonnées'
  }
};

export const defaultReviews = [
  {
    name: 'Kofi Mensah',
    location: 'Airport Residential Area, Accra',
    rating: 5,
    text: 'Glasswater completed the fit‑out for our new corporate office ahead of schedule. The craftsmanship in the glass partitioning and finishing is pristine. Highly recommended!',
    date: 1717843200000
  },
  {
    name: 'Naa Adjeley',
    location: 'East Legon, Accra',
    rating: 5,
    text: 'We had persistent dampness and roof leaks in our warehouse for years. Glasswater applied their multi‑layer liquid waterproofing system, and we have been bone dry ever since.',
    date: 1718016000000
  },
  {
    name: 'Ekow Benson',
    location: 'Tema Community 6',
    rating: 4,
    text: 'Superb project management and structural engineering. Their pool construction division is also state‑of‑the‑art. Communication was excellent throughout the project.',
    date: 1718275200000
  }
];

export const defaultReviewsFR = [
  {
    name: 'Kofi Mensah',
    location: 'Airport Residential Area, Accra',
    rating: 5,
    text: 'Glasswater a terminé l\'aménagement de notre nouveau siège social avant la date prévue. Le savoir-faire dans les cloisons vitrées et les finitions est impeccable. Fortement recommandé !',
    date: 1717843200000
  },
  {
    name: 'Naa Adjeley',
    location: 'East Legon, Accra',
    rating: 5,
    text: 'Nous avions une humidité persistante et des fuites de toit dans notre entrepôt depuis des années. Glasswater a appliqué son système d\'étanchéité liquide multicouche et nous sommes au sec depuis.',
    date: 1718016000000
  },
  {
    name: 'Ekow Benson',
    location: 'Tema Community 6',
    rating: 4,
    text: 'Superbe gestion de projet et ingénierie structurelle. Leur division de construction de piscines est également à la pointe de la technologie. La communication a été excellente tout au long du projet.',
    date: 1718275200000
  }
];

export function getReviews(lang) {
  return lang === 'fr' ? defaultReviewsFR : defaultReviews;
}


